pcs = {
    0: "Crono",
    1: "Marle",
    2: "Lucca",
    3: "Robo",
    4: "Frog",
    5: "Ayla",
    6: "Magus",
    7: "Epoch"
}

locations = [
    (0x10f, "Special Purpose Area [includes Bike Race & after Zeal Fall CS]"),
    (0x2, "Crono's Room"),
    (0x1, "Crono's Kitchen"),
    (0x5, "Millenial Fair"),
    (0x1b7, "Leene Square"),
    (0x8, "Telepod Exhibit"),
    (0x71, "Truce Canyon Portal"),
    (0x70, "Truce Canyon"),
    (0x1f1, "Middle Ages [OVERWORLD]"),
    (0x77, "Guardia Forest (Middle Ages)"),
    (0x78, "Guardia Throneroom (Middle Ages)"),
    (0x1d4, "Guardia Queen's Tower (Middle Ages)"),
    (0x7a, "Guardia Queen's Chamber (Middle Ages)"),
    (0x6c, "Lucca Explains Paradoxes"),
    (0x81, "Manoria Sanctuary"),
    (0x82, "Manoria Main Hall"),
    (0xc7, "Manoria Confinement"),
    (0x83, "Manoria Headquarters"),
    (0x84, "Manoria Royal Guard Hall"),
    (0xc6, "Manoria Command"),
    (0x13, "Guardia Forest (Present)"),
    (0x15, "Guardia Throneroom (Present)"),
    (0x1b, "Courtroom"),
    (0x1c, "Prison Catwalks"),
    (0x1d, "Prison Supervisor's Office"),
    (0x47, "Prison Cells"),
    (0x48, "Prison Stairwells"),
    (0x1e9, "Guardia Prison Tower"),
    (0x14, "Guardia Forest Dead End"),
    (0xd0, "Bangor Dome"),
    (0x1f2, "Future [OVERWORLD]"),
    (0xd4, "Lab 16 West"),
    (0xd5, "Lab 16 East"),
    (0xd6, "Arris Dome"),
    (0xd8, "Arris Dome Auxiliary Console"),
    (0xdd, "Arris Dome Rafters"),
    (0xdb, "Arris Dome Guardian Chamber"),
    (0x158, "Arris Dome Food Locker"),
    (0xd7, "Arris Dome Infestation"),
    (0xd9, "Arris Dome Lower Commons"),
    (0xda, "Arris Dome Command Central"),
    (0xdf, "Lab 32 West Entrance"),
    (0xe1, "Lab 32 East Entrance"),
    (0xe2, "Proto Dome"),
    (0xe4, "Factory Ruins Entrance"),
    (0xe5, "Factory Ruins Auxiliary Console"),
    (0xe6, "Factory Ruins Security Center"),
    (0xeb, "Factory Ruins Power Core"),
    (0xe3, "Proto Dome Portal"),
    (0x1d0, "End of Time"),
    (0x1d1, "Spekkio"),
    (0x24, "Medina Portal Medina Residence"),
    (0x21, "Medina Elder's House 1F"),
    (0x22, "Medina Elder's House 2F"),
    (0x30, "Heckran Cave Entrance"),
    (0x31, "H.Cave Underground River"),
    (0x2f, "Heckran Cave Passageways"),
    (0x87, "Zenan Bridge (Middle Ages)"),
    (0x7b, "Guardia Kitchen (Middle Ages)"),
    (0x8b, "Sandorino Market"),
    (0x91, "Denadoro Entrance"),
    (0x8e, "Denadoro South Face"),
    (0x92, "Denadoro Lower East Face"),
    (0x8f, "Denadoro Cave of the Masamune Exterior"),
    (0x93, "Denadoro Upper East Face"),
    (0x96, "Denadoro Gauntlet"),
    (0x90, "Denadoro North Face"),
    (0x94, "Denadoro Mountain Vista"),
    (0x95, "Denadoro West Face"),
    (0x97, "Denadoro Cave of the Masamune"),
    (0x9d, "Porre Market (Middle Ages)"),
    (0x98, "Tata's House 1F"),
    (0x9a, "Porre Elder's House [JERKY]"),
    (0x8c, "Cursed Woods"),
    (0x8d, "Frog's Burrow"),
    (0x28, "Melchior's Kitchen"),
    (0x110, "Mystic Mtn Portal"),
    (0x111, "Mystic Mtn Base"),
    (0x112, "Mystic Mtn Gulch"),
    (0x1f3, "Prehistoric [OVERWORLD]"),
    (0x113, "Chief's Hut"),
    (0x118, "Ioka Meeting Site (Party)"),
    (0x117, "Ioka Meeting Site"),
    (0x11a, "Forest Maze"),
    (0x11b, "Reptite Lair Entrance"),
    (0x11c, "Reptite Lair 1F"),
    (0x11d, "Reptite Lair Weevil Burrows B1"),
    (0x11e, "Reptite Lair Weevil Burrows B2"),
    (0x11f, "Reptite Lair Commons"),
    (0x120, "Reptite Lair Tunnel"),
    (0x121, "Reptite Lair Azala's Room"),
    (0x29, "Melchior's Workshop"),
    (0xce, "Guardia Throneroom Cyrus's Final Mission"),
    (0xcc, "Guardia Forest Frog King Battle"),
    (0xcd, "Denadoro Cyrus's Last Battle"),
    (0xa3, "Magic Cave Exterior"),
    (0xa4, "Magic Cave Interior"),
    (0xa5, "Castle Magus Exterior"),
    (0xa6, "Castle Magus Entrance"),
    (0x1d5, "Castle Magus Corridor of Combat"),
    (0xa9, "Castle Magus Throne of Strength"),
    (0xab, "Castle Magus Hall of Deceit"),
    (0x7d, "Castle Magus Doppleganger Corridor"),
    (0xad, "Castle Magus Throne of Magic"),
    (0xaa, "Castle Magus Hall of Aggression"),
    (0xa7, "Castle Magus Chamber of Guillotines"),
    (0xb0, "Castle Magus Lower Battlements"),
    (0xa8, "Castle Magus Chamber of Pits"),
    (0x1be, "Castle Magus Upper Battlements"),
    (0xaf, "Castle Magus Hall of Apprehension"),
    (0x1d6, "Castle Magus Hall of Ambush"),
    (0xae, "Castle Magus Throne of Defense"),
    (0x1bf, "Castle Magus Grand Stairway"),
    (0xac, "Castle Magus Inner Sanctum"),
    (0x124, "Laruba Ruins"),
    (0x125, "Dactyl Nest, Lower"),
    (0x126, "Dactyl Nest, Upper"),
    (0x127, "Dactyl Nest Summit"),
    (0x12b, "Tyrano Lair Entrance"),
    (0x1ae, "Tyrano Lair Main Cell"),
    (0x12e, "Tyrano Lair Antechambers"),
    (0x12a, "Tyrano Lair Exterior"),
    (0x131, "Tyrano Lair Room of Vertigo"),
    (0x12f, "Tyrano Lair Storage"),
    (0x130, "Tyrano Lair Nizbel's Room"),
    (0x12c, "Tyrano Lair Throneroom"),
    (0x12d, "Tyrano Lair Keep"),
    (0x105, "Prehistoric Canyon"),
    (0x133, "Lair Ruins Portal"),
    (0x15f, "Dark Ages Portal"),
    (0x1f4, "Dark Ages [OVERWORLD]"),
    (0x151, "Skyway? (TBD)"),
    (0x161, "Land Bridge (TBD)"),
    (0x1f5, "Kingdom of Zeal [OVERWORLD]"),
    (0x150, "Land Bridge (TBD)"),
    (0x162, "Skyway (TBD)"),
    (0x164, "Skyway (TBD)"),
    (0x160, "Land Bridge (TBD)"),
    (0x185, "Zeal Teleporters"),
    (0x191, "Zeal Palace"),
    (0x192, "Zeal Palace Hallway"),
    (0x148, "Zeal Palace Schala's Room"),
    (0x149, "Zeal Palace Regal Hall"),
    (0x14a, "Zeal Palace Corridor to the Mammon Machine"),
    (0x14b, "Zeal Palace Hall of the Mammon Machine"),
    (0x14c, "Zeal Palace Zeal Throneroom"),
    (0x14d, "Zeal Palace Hall of the Mammon Machine (Night)"),
    (0xf1, "Keeper's Dome [cutscene & real]"),
    (0x2a, "Forest Ruins Pyramid"),
    (0x74, "Truce Inn 1F (Middle Ages)"),
    (0x75, "Truce Inn 2F (Middle Ages)"),
    (0x9f, "Sunken Desert Entrance"),
    (0xa0, "Sunken Desert Parasytes"),
    (0xa1, "Sunken Desert Devourer"),
    (0x9e, "Fiona's Villa"),
    (0xc, "Truce Inn (Present)"),
    (0x1e6, "Guardia King's Tower (Present)"),
    (0x39, "Fiona's Shrine"),
    (0x1b4, "Fiona's Forest Campfire"),
    (0x53, "Fiona's Forest Recriminations Lucca's Gate"),
    (0xa, "Lucca's Room"),
    (0x3, "Lucca's Kitchen"),
    (0x4, "Lucca's Workshop"),
    (0x1d2, "Apocalypse Lavos [Headless map]"),
    (0x1f7, "1999 World Map [OVERWORLD]"),
    (0xe0, "Lab 32"),
    (0xec, "Sewer Access B1"),
    (0xed, "Sewer Access B2"),
    (0xf2, "Keeper's Dome Corridor"),
    (0xf3, "Keeper's Dome Hanger"),
    (0x1b0, "Flying Epoch"),
    (0x182, "Algetty Entrance"),
    (0x17c, "Algetty"),
    (0x184, "The Beast's Nest"),
    (0x18a, "Mt. Woe Middle Eastern Face"),
    (0x188, "Mt. Woe Western Face"),
    (0x189, "Mt. Woe Lower Eastern Face"),
    (0x18b, "Mt. Woe Upper Eastern Face"),
    (0x18d, "Mt. Woe Summit"),
    (0x17e, "Algetty Elder's Grotto"),
    (0x14e, "Zeal Palace Zeal Throneroom (Night)"),
    (0x194, "Ocean Palace Entrance"),
    (0x19f, "Ocean Palace Throneroom [Cutscene & real]"),
    (0x195, "Ocean Palace Piazza"),
    (0x196, "Ocean Palace Side Rooms [incl. Scout Skips]"),
    (0x197, "Ocean Palace Forward Area"),
    (0x198, "Ocean Palace B3 Landing"),
    (0x199, "Ocean Palace Grand Stairwell"),
    (0x19a, "Ocean Palace B20 Landing"),
    (0x19b, "Ocean Palace Southern Access Lift"),
    (0x1a0, "Ocean Palace (TBD) [ELEVATOR]"),
    (0x1a2, "Ocean Palace Western Access Lift"),
    (0x19c, "Ocean Palace Security Pool"),
    (0x19d, "Ocean Palace Security Esplanade"),
    (0x19e, "Ocean Palace Regal Antechamber [Golemtwins]"),
    (0x1a7, "Ocean Palace Time Freeze [Crono dies]"),
    (0x1ee, "Paradise Lost"),
    (0x165, "Kajar [real & Fall-of-Zeal scene]"),
    (0x1ed, "Algetty Tsunami"),
    (0x1a9, "Last Village Empty Hut"),
    (0x1f6, "Last Village (12000 World Map) [OVERWORLD]"),
    (0x1aa, "Last Village Shop"),
    (0x1a8, "Last Village Commons"),
    (0x173, "Blackbird Cell"),
    (0x16c, "Blackbird Right Port"),
    (0x16e, "Blackbird Overhead"),
    (0x178, "Blackbird Ducts"),
    (0x171, "Blackbird Forward Halls"),
    (0x176, "Blackbird Inventory"),
    (0x1de, "Blackbird Wing Access"),
    (0x16b, "Blackbird Left Wing"),
    (0x16f, "Blackbird Hanger"),
    (0x179, "Reborn Epoch [Dalton fight]"),
    (0x1e1, "Death of the Blackbird"),
    (0x1d8, "Apocalypse Epoch (Last Village)"),
    (0x1ac, "North Cape"),
    (0x1dd, "(Epoch) Emergence of the Black Omen"),
    (0xbc, "Choras Cafe"),
    (0x3e, "Choras Inn (Present)"),
    (0x3d, "Choras Carpenter's Residence"),
    (0xba, "Choras Carpenter's Residence 1F (Middle Ages)"),
    (0x41, "Northern Ruins Entrance (600 & 1000)"),
    (0x42, "Northern Ruins Basement Corridor (600 & 1000)"),
    (0x49, "Northern Ruins Hero's Grave (600 & 1000)"),
    (0x1d9, "End of Time Epoch"),
    (0xfb, "Sun Palace"),
    (0x147, "Sunkeep (Prehistoric)"),
    (0x40, "Sun Keep (Present)"),
    (0x32, "Porre Mayor's Manor 1F (Present)"),
    (0xff, "Sun Keep (Future)"),
    (0xc3, "Giant's Claw Entrance [incl. Lizards]"),
    (0x129, "Giant's Claw Lair Throneroom"),
    (0x6e, "Ancient Tyrano Lair Traps"),
    (0xc4, "Giant's Claw Caverns"),
    (0x6f, "Ancient Tyrano Lair Nizbel's Room [escape ladder]"),
    (0x6d, "Ancient Tyrano Lair"),
    (0x128, "Giant's Claw Lair Entrance"),
    (0xc5, "Giant's Claw Last Tyranno"),
    (0xf8, "Geno Dome Entrance"),
    (0xf9, "Geno Dome Conveyor Entrance"),
    (0x7e, "Geno Dome Main Conveyor"),
    (0xfa, "Geno Dome Conveyor Exit"),
    (0x100, "Geno Dome Labs"),
    (0x7f, "Geno Dome Elevator [both]"),
    (0x10c, "Geno Dome Mainframe (Atropos)"),
    (0x80, "Geno Dome Long Corridor"),
    (0x10b, "Geno Dome Robot Elevator Access"),
    (0x1e8, "Guardia Lawgiver's Tower"),
    (0x1b9, "Courtroom Lobby"),
    (0x1b6, "Courtroom King's Trial"),
    (0x1a, "Guardia Basement"),
    (0x1b8, "Guardia Rear Storage [Prism]"),
    (0x6, "Gato's Exhibit"),
    (0x1b2, "Bekkler's Lab"),
    (0xf4, "Death Peak Entrance"),
    (0xf5, "Death Peak South Face"),
    (0xf6, "Death Peak Southeast Face"),
    (0x108, "Death Peak Cave [1st Spawn]"),
    (0x107, "Death Peak Lower North Face"),
    (0xf7, "Death Peak Northeast Face [2nd Spawn]"),
    (0x106, "Death Peak Upper North Face"),
    (0x104, "Death Peak Northwest Face [Egg Slide]"),
    (0x1ef, "Death Peak Guardian Spawn [3rd Spawn]"),
    (0x109, "Death Peak Summit"),
    (0x1ad, "Death Peak Summit [Hug scene]"),
    (0xb1, "Ozzie's Fort Entrance"),
    (0xb7, "Ozzie's Fort Throne of Impertinence [Flea]"),
    (0xb2, "Ozzie's Fort Hall of Disregard"),
    (0xb8, "Ozzie's Fort Throne of Ineptitude [Slash]"),
    (0xb3, "Ozzie's Fort Chamber of Kitchen Knives"),
    (0xb4, "Ozzie's Fort Last Stand [big fight]"),
    (0xb5, "Ozzie's Fort Throne of Incompetence"),
    (0x1c1, "Black Omen Entrance"),
    (0x134, "Black Omen 1F Entrance [Megamutan]"),
    (0x135, "Black Omen 1F Walkway [Goon]"),
    (0x136, "Black Omen 1F Defense Corridor [Panel]"),
    (0x137, "Black Omen 1F Stairway [Eyeball1]"),
    (0x138, "Black Omen 3F Walkway [Metalmute]"),
    (0x61, "Black Omen 3F Teleporter [entries: 1st,3rd]"),
    (0x62, "Black Omen 45F Teleporter [exits: 2nd,4th]"),
    (0x63, "Black Omen Platform [all 4 landings]"),
    (0x64, "Black Omen Platform Shaft [downward]"),
    (0x139, "Black Omen Auxilary Command [Trap Floors 1]"),
    (0x13a, "Black Omen (TBD) Trap Floors 2"),
    (0x13b, "Black Omen (TBD) Nu Shop"),
    (0x13c, "Black Omen (TBD) Tubster (lower/upper)"),
    (0x13d, "Black Omen (TBD) Cybot/Rumin"),
    (0x13e, "Black Omen (TBD) Eyeball 2"),
    (0x13f, "Black Omen (TBD) Tubster"),
    (0x140, "Black Omen (TBD) teleport"),
    (0x141, "Black Omen (TBD) teleport"),
    (0x142, "Black Omen (TBD) Aliens"),
    (0x143, "Black Omen (TBD) Gigamutant"),
    (0x65, "Black Omen Platform Shaft (upward)"),
    (0x144, "Black Omen (TBD) Synchrite fight"),
    (0x145, "Black Omen (TBD) Teramutant"),
    (0x146, "Black Omen (TBD) walkway to Spawn"),
    (0x60, "Black Omen Lavos Spawn"),
    (0x1c2, "Black Omen Omega Defense"),
    (0x1c3, "Black Omen Seat of Agelessness [Zeal1]"),
    (0x1a6, "Time Distortion Mammon Machine"),
    (0x6b, "Black Omen Celestial Gate [Zeal fight]"),
    (0x1d3, "Lavos Fight"),
    (0x15b, "Prison Catwalks (Battle with Lavos)"),
    (0x15a, "Arris Dome Guardian Chamber (Battle with Lavos)"),
    (0x15c, "Heckran Cave (Battle with Lavos)"),
    (0x15d, "Zenan Bridge (Battle with Lavos)"),
    (0x15e, "Cave of the Masamune (Battle with Lavos)"),
    (0x1c8, "Reptite Lair (Battle with Lavos)"),
    (0x1c9, "Castle Magus Inner Sanctum (Battle with Lavos)"),
    (0x1ca, "Tyrano Lair Keep (Battle with Lavos)"),
    (0x1cb, "Mt. Woe Summit (Battle with Lavos)"),
    (0x1da, "Lavos Tunnel"),
    (0x1db, "Lavos Core"),
    (0x1df, "Tesseract"),
    (0x52, "Ending Selector [NewGame+ unlocks upon 052 loading]"),
    (0x7, "Prehistoric Exhibit"),
    (0x9, "Lara's Room"),
    (0xb, "Ending Selector (not used?)"),
    (0xd, "Truce Mayor's Manor 1F"),
    (0xe, "Truce Mayor's Manor 2F"),
    (0xf, "Truce Single Woman Residence"),
    (0x10, "Truce Happy Screaming Couple Residence"),
    (0x11, "Truce Market (Present)"),
    (0x12, "Truce Ticket Office"),
    (0x16, "King's Chamber (Present)"),
    (0x17, "Queen's Chamber (Present)"),
    (0x18, "Guardia Kitchen (Present)"),
    (0x19, "Guardia Barracks (Present)"),
    (0x1e, "Prison Torture Storage Room"),
    (0x1f, "Medina Square"),
    (0x20, "Zenan Bridge (Present)"),
    (0x23, "Medina Inn"),
    (0x25, "Ending: Legendary Hero"),
    (0x26, "Guardia Throneroom (Ending)"),
    (0x27, "Medina Market"),
    (0x2b, "Cursed Woods (Ending)"),
    (0x2c, "Leene Square (Future)"),
    (0x2d, "Denadoro Mtn Vista (Ending)"),
    (0x2e, "Castle Magus Throne (Ending)"),
    (0x33, "Porre Mayor's Manor 2F (Present)"),
    (0x34, "Porre Residence (Present)"),
    (0x35, "Snail Stop"),
    (0x36, "Porre Market (Present)"),
    (0x37, "Porre Inn (Present)"),
    (0x38, "Porre Ticket Office"),
    (0x3a, "Choras Mayor's Manor 1F"),
    (0x3b, "Choras Mayor's Manor 2F"),
    (0x3c, "Castle Magus Hall (Ending)"),
    (0x3f, "West Cape Toma's Grave"),
    (0x43, "Northern Ruins Landing (Present)"),
    (0x44, "Northern Ruins Antechamber (Present)"),
    (0x45, "Northern Ruins Vestibule (Present)"),
    (0x46, "Northern Ruins Back Room (Present)"),
    (0x4a, "Unknown"),
    (0x4b, "Prison Exterior"),
    (0x4c, "Unknown (Lavos Spawn)"),
    (0x4d, "Unknown (Lavos Spawn)"),
    (0x4e, "Unknown (Lavos Spawn)"),
    (0x4f, "Guardia Throneroom (Ending: Moonlight Parade)"),
    (0x50, "Millenial Fair (Ending: Moonlight Parade)"),
    (0x51, "Leene Square (Ending: Moonlight Parade)"),
    (0x54, "End of Time (Ending: Moonlight Parade)"),
    (0x55, "Telepod Exhibit (Ending: Moonlight Parade)"),
    (0x56, "Death Peak Summit (Ending: Moonlight Parade)"),
    (0x57, "Manoria Sanctuary (Ending: The Successor of Guardia)"),
    (0x58, "The End"),
    (0x59, "Zenan Bridge (Ending: Moonlight Parade)"),
    (0x5a, "Prison Catwalks (Ending: Moonlight Parade)"),
    (0x5b, "Ending: People of the Times (Part 1)"),
    (0x5c, "Ending: People of the Times (Part 2)"),
    (0x5d, "Ending: People of the Times (Part 3)"),
    (0x5e, "Ending: People of the Times (Part 4)"),
    (0x5f, "Ending: People of the Times (Part 5)"),
    (0x66, "Black Omen Celestial Gate (no map)"),
    (0x67, "Black Omen Celestial Gate (no map)"),
    (0x68, "Black Omen Celestial Gate (no map)"),
    (0x69, "Black Omen Celestial Gate (no map)"),
    (0x6a, "Black Omen Celestial Gate (no map)"),
    (0x72, "Truce Couple's Residence (Middle Ages)"),
    (0x73, "Truce Smithy's Residence"),
    (0x76, "Truce Market (Middle Ages)"),
    (0x79, "Guardia King's Chamber (Middle Ages)"),
    (0x7c, "Guardia Barracks (Middle Ages)"),
    (0x85, "Zenan Bridge (Wrecked)"),
    (0x86, "Zenan Bridge (Middle Ages, no map)"),
    (0x88, "Sandorino Pervert Residence"),
    (0x89, "Sandorino Elder's House"),
    (0x8a, "Sandorino Inn"),
    (0x99, "Tata's House 2F"),
    (0x9b, "Porre Cafe (Middle Ages)"),
    (0x9c, "Porre Inn (Middle Ages)"),
    (0xa2, "Ozzie's Fort Entrance (no map)"),
    (0xb6, "Ozzie's Fort Throne of Impertinence (wrong map)"),
    (0xb9, "Choras Old Couple Residence (Middle Ages)"),
    (0xbb, "Choras Carpenter's Residence 2F (Middle Ages)"),
    (0xbd, "Choras Inn (Middle Ages)"),
    (0xbe, "Choras Market (Middle Ages)"),
    (0xbf, "Sun Keep (Middle Ages)"),
    (0xc0, "(empty map)"),
    (0xc1, "(empty map)"),
    (0xc2, "(empty map)"),
    (0xc8, "Manoria Shrine Antechamber"),
    (0xc9, "Manoria Storage"),
    (0xca, "Manoria Kitchen"),
    (0xcb, "Manoria Shrine"),
    (0xcf, "Schala's Room (no map)"),
    (0xd1, "Bangor Dome Sealed Room"),
    (0xd2, "Trann Dome"),
    (0xd3, "Trann Dome Sealed Room"),
    (0xdc, "Arris Dome Sealed Room"),
    (0xde, "Reptite Lair 2F (escape ladder)"),
    (0xe7, "Factory Ruins Crane Room"),
    (0xe8, "Factory Ruins Infestation"),
    (0xe9, "Factory Ruins Crane Control Room"),
    (0xea, "Factory Ruins Information Archive (XABY)"),
    (0xee, "Ending: Dream Team (no map) (TBD)"),
    (0xef, "Ending: A Slide Show?"),
    (0xf0, "Ending: Goodnight"),
    (0xfc, "Millenial Fair (Ending: Dino Age)"),
    (0xfd, "Sun Keep (Last Village)"),
    (0xfe, "Skill Tutorial"),
    (0x101, "Geno Dome Storage (south,locked)"),
    (0x102, "Geno Dome Robot Hub (north)"),
    (0x103, "Factory Ruins xData Corex (Robot Storage!)"),
    (0x10a, "Ending: Dream Team (no map) (TBD)"),
    (0x10d, "Geno Dome Waste Disposal (soylent room)"),
    (0x10e, "Leene's Square (Ending: Dino Age)"),
    (0x114, "Ioka Southwestern Hut"),
    (0x115, "Ioka Trading Post"),
    (0x116, "Ioka Sweet Water Hut"),
    (0x119, "Forest Maze Entrance (no entry)"),
    (0x122, "Reptite Lair Access Shaft (escape ladder)"),
    (0x123, "Hunting Range"),
    (0x132, "Debug Room?"),
    (0x14f, "Enhasa (wrong map)"),
    (0x152, "Present Age Home Room (Ending: The Dream Project)"),
    (0x153, "Prehistoric Age Jungle (Ending: The Dream Project)"),
    (0x154, "Dark Age Ocean Palace Room (Ending: The Dream Project)"),
    (0x155, "Present Age Jail Cell (Ending: The Dream Project)"),
    (0x156, "Dark Age Earthbound Room (Ending: The Dream Project)"),
    (0x157, "Present Age Northern Ruins Room (Ending: The Dream Project)"),
    (0x159, "Lucca's Workshop (Ending: The Oath)"),
    (0x163, "Enhasa"),
    (0x166, "Kajar Study"),
    (0x167, "Kajar Belthasar's Private Room"),
    (0x168, "Kajar Magic Lab"),
    (0x169, "Zeal Palace Belthasar's Private Room"),
    (0x16a, "Blackbird Scaffolding"),
    (0x16d, "Blackbird Left Port"),
    (0x170, "Blackbird Rear Halls"),
    (0x172, "Blackbird Treasury"),
    (0x174, "Blackbird Barracks"),
    (0x175, "Blackbird Armory 3"),
    (0x177, "Blackbird Lounge"),
    (0x17a, "Future Age Room (Ending: The Dream Project)"),
    (0x17b, "End of Time (Ending: The Dream Project)"),
    (0x17d, "Algetty Inn"),
    (0x17f, "Algetty Commoner Grotto"),
    (0x180, "Algetty Shop"),
    (0x181, "Algetty Tsunami (wrong map)"),
    (0x183, "The Beast's Nest (wrong map)"),
    (0x186, "Prehistoric Hut (Ending: The Dream Project)"),
    (0x187, "Castle Magus Room (Ending: The Dream Project)"),
    (0x18c, "Mt. Woe Summit (wrong map)"),
    (0x18e, "Leene Square (Ending: What the Prophet Seeks)"),
    (0x18f, "Crono's Kitchen (Ending: What the Prophet Seeks)"),
    (0x190, "The End (Ending: Multiple?)"),
    (0x193, "Zeal Palace Study"),
    (0x1a1, "Ocean Palace Eastern Access Lift"),
    (0x1a3, "Ocean Palace Time Freeze (wrong map)"),
    (0x1a4, "Ocean Palace Time Freeze (wrong map)"),
    (0x1a5, "Ocean Palace Time Freeze (wrong map)"),
    (0x1ab, "Last Village Residence"),
    (0x1af, "Title Screen (wrong map)"),
    (0x1b3, "Magic Cave Exterior (all visits after the cutscene)"),
    (0x1b5, "Factory Ruins (TBD) Fight gauntlet"),
    (0x1ba, "Blackbird Access Shaft"),
    (0x1bb, "Blackbird Armory 2"),
    (0x1bc, "Blackbird Armory 1"),
    (0x1bd, "Blackbird Storage"),
    (0x1c0, "(Bad Event Data Packet)"),
    (0x1c4, "(Bad Event Data Packet)"),
    (0x1c5, "(Bad Event Data Packet)"),
    (0x1c6, "(Bad Event Data Packet)"),
    (0x1c7, "(Bad Event Data Packet)"),
    (0x1cc, "Credits (TBD)"),
    (0x1cd, "(Empty Data)"),
    (0x1ce, "(Empty Data)"),
    (0x1cf, "(Empty Data)"),
    (0x1d7, "Castle Magus Dungeon"),
    (0x1dc, "Truce Dome"),
    (0x1e0, "Guardia King's Tower (Middle Ages)"),
    (0x1e2, "Blackbird (no exits)"),
    (0x1e3, "Blackbird (no exits)"),
    (0x1e4, "Blackbird (no exits)"),
    (0x1e5, "Blackbird (no exits)"),
    (0x1e7, "Guardia Queen's Tower (Present)"),
    (0x1ea, "Ancient Tyrano Lair Room of Vertigo (Giant's Claw Teleport Room)"),
    (0x1eb, "(empty map)"),
    (0x1ec, "(empty map)"),
    (0x1f8, "(empty map)"),
    (0x1f9, "(empty map)"),
    (0x1fa, "(empty map)"),
    (0x1fb, "(empty map)"),
    (0x1fc, "(empty map)"),
    (0x1fd, "(empty map)"),
    (0x1fe, "(empty map)"),
    (0x1ff, "(empty map)")
]

npcs = {
    0x00: "Melchior",
    0x01: "King Guardia XXXIII [1000 A.D.]",
    0x02: "Johnny",
    0x03: "Queen Leene",
    0x04: "Tata",
    0x05: "Toma",
    0x06: "Kino",
    0x07: "Chancellor (green) [1000 A.D.]",
    0x08: "Dactyl",
    0x09: "Schala",
    0x0A: "Janus",
    0x0B: "Chancellor (brown) [600 A.D.]",
    0x0C: "Belthasar",
    0x0D: "Middle Ages/Present Age villager - woman",
    0x0E: "Middle Ages/Present Age villager - young man",
    0x0F: "Middle Ages/Present Age villager - young woman",
    0x10: "Middle Ages/Present Age villager - soldier",
    0x11: "Middle Ages/Present Age villager - old man",
    0x12: "Middle Ages/Present Age villager - old woman",
    0x13: "Middle Ages/Present Age villager - little boy",
    0x14: "Middle Ages/Present Age villager - little girl",
    0x15: "Middle Ages/Present Age villager - waitress",
    0x16: "Middle Ages/Present Age villager - shopkeeper",
    0x17: "Nun",
    0x18: "Knight captain [600 A.D.]",
    0x19: "Middle Ages/Present Age villager - man",
    0x1A: "Dome survivor - man",
    0x1B: "Dome survivor - woman",
    0x1C: "Doan",
    0x1D: "Dome survivor - little girl",
    0x1E: "Prehistoric villager - man with club",
    0x1F: "Prehistoric villager - woman in green dress",
    0x20: "Prehistoric villager - little girl",
    0x21: "Prehistoric villager - old man",
    0x22: "Zeal citizen - man",
    0x23: "Zeal citizen - woman",
    0x24: "Zeal citizen - researcher with glasses",
    0x25: "Crono's mom",
    0x26: "Middle Ages/Present Age villager - little girl with purple hair",
    0x27: "Middle Ages/Present Age villager - man",
    0x28: "Middle Ages/Present Age villager - woman with purple hair",
    0x29: "Middle Ages/Present Age villager - young man",
    0x2A: "Middle Ages/Present Age villager - young woman",
    0x2B: "Middle Ages/Present Age villager - soldier",
    0x2C: "Middle Ages/Present Age villager - old man",
    0x2D: "Middle Ages/Present Age villager - old woman",
    0x2E: "Middle Ages/Present Age villager - little boy",
    0x2F: "Middle Ages/Present Age villager - little girl",
    0x30: "Middle Ages/Present Age villager - waitress with purple hair",
    0x31: "Middle Ages/Present Age villager - shopkeeper",
    0x32: "Nun",
    0x33: "Guardia knight [600 A.D.]",
    0x34: "Middle Ages/Present Age villager - man",
    0x35: "Cyrus",
    0x36: "Young Glenn",
    0x37: "King Guardia XXI [600 A.D.]",
    0x38: "Strength Test Machine part (Millennial Fair)",
    0x39: "Middle Ages/Present Age villager - old man *2C duplicate/NOT USED*",
    0x3A: "Zeal citizen - researcher with glasses",
    0x3B: "Cat",
    0x3C: "False prophet Magus",
    0x3D: "Melchior in gray robe/NOT USED",
    0x3E: "Prehistoric villager - man carrying club with purple hair",
    0x3F: "Prehistoric villager - woman with purple hair",
    0x40: "Prehistoric villager - little girl with purple hair",
    0x41: "Algetty earthbound one - man",
    0x42: "Algetty earthbound one - woman",
    0x43: "Algetty earthbound one - old man",
    0x44: "Algetty earthbound one - child",
    0x45: "Princess Nadia",
    0x46: "Guardia Castle chef",
    0x47: "Trial judge",
    0x48: "Gaspar",
    0x49: "Fiona",
    0x4A: "Queen Zeal",
    0x4B: "Guard (enemy)",
    0x4C: "Reptite",
    0x4D: "Kilwala",
    0x4E: "Blue imp",
    0x4F: "Middle Ages/Present Age villager - man",
    0x50: "Middle Ages/Present Age villager - woman",
    0x51: "G.I. Jogger",
    0x52: "Millennial Fair visitor - old man",
    0x53: "Millennial Fair visitor - woman",
    0x54: "Millennial Fair visitor - little boy",
    0x55: "Millennial Fair visitor - little girl",
    0x56: "Lightning bolt",
    0x57: "Opened time portal - upper half",
    0x58: "Opened time portal - lower half",
    0x59: "Millennial Fair shopkeeper",
    0x5A: "Guillotine blade",
    0x5B: "Guillotine chain",
    0x5C: "Conveyor machine",
    0x5D: "Tombstone",
    0x5E: "Giant soup bowl",
    0x5F: "Magus statue",
    0x60: "Dreamstone",
    0x61: "Gate Key",
    0x62: "Soda can",
    0x63: "Pendant",
    0x64: "Poyozo doll",
    0x65: "Pink lunch bag",
    0x66: "UNUSED",
    0x67: "Red knife ",
    0x68: "Broken Masamune blade",
    0x69: "Slice of cake",
    0x6A: "Trash can on its side",
    0x6B: "Piece of cheese",
    0x6C: "Barrel",
    0x6D: "UNUSED",
    0x6E: "Dead sunstone",
    0x6F: "Metal mug",
    0x70: "Blue star",
    0x71: "Giant blue star",
    0x72: "Red flame",
    0x73: "Giant red flame",
    0x74: "Explosion ball",
    0x75: "Giant explosion ball",
    0x76: "Smoke trail/NOT USED",
    0x77: "Hero's medal",
    0x78: "Balcony shadow",
    0x79: "Save point",
    0x7A: "Prehistoric villager - drummer",
    0x7B: "Prehistoric villager - log drummer",
    0x7C: "White explosion outline",
    0x7D: "Leene's bell",
    0x7E: "Bat hanging upside down",
    0x7F: "Computer screen",
    0x80: "Water splash",
    0x81: "Explosion",
    0x82: "Robo power-up sparks",
    0x83: "Leaves falling/NOT USED",
    0x84: "3 coins spinning/NOT USED",
    0x85: "Hole in the ground",
    0x86: "Cooking smoke",
    0x87: "3 small explosion clouds",
    0x88: "Wind element spinning",
    0x89: "Water element/NOT USED",
    0x8A: "Dirt mound",
    0x8B: "Masamune spinning",
    0x8C: "Music note/NOT USED",
    0x8D: "Small fish/NOT USED",
    0x8E: "Water splash/NOT USED",
    0x8F: "Lightning bolt/NOT USED",
    0x90: "Unknown graphics/NOT USED",
    0x91: "UNUSED",
    0x92: "Small rock",
    0x93: "Small rock *92 duplicate/NOT USED*",
    0x94: "Small rock *92 duplicate/NOT USED*",
    0x95: "Rainbow shell",
    0x96: "Shadow (beds)",
    0x97: "Closed portal",
    0x98: "Balloon/NOT USED",
    0x99: "Light green bush",
    0x9A: "Shadow on the ground/NOT USED",
    0x9B: "Brown dreamstone/NOT USED",
    0x9C: "Crane machine",
    0x9D: "UNUSED",
    0x9E: "Dripping water/NOT USED",
    0x9F: "Cupboard doors",
    0xA0: "Brown stones/NOT USED",
    0xA1: "Dark green bush",
    0xA2: "Journal",
    0xA3: "Norstein Bekkler",
    0xA4: "Rat",
    0xA5: "Sparks from guillotine blade",
    0xA6: "Zeal teleporter",
    0xA7: "Ocean palace teleporter",
    0xA8: "Truce Dome director",
    0xA9: "Epoch seats",
    0xAA: "Robot",
    0xAB: "Red star",
    0xAC: "Sealed portal",
    0xAD: "Animated Zz (sleeping) icon",
    0xAE: "Flying map Epoch",
    0xAF: "Gray cat",
    0xB0: "Yellow cat",
    0xB1: "Alfador",
    0xB2: "Time egg",
    0xB3: "Zeal citizen - man (cast ending)",
    0xB4: "Zeal citizen - woman",
    0xB5: "Potted plant",
    0xB6: "Kid with purple hair (Glenn/Cyrus cutscene)",
    0xB7: "Sealed chest",
    0xB8: "Squirrel (Programmer's Ending)",
    0xB9: "Blue poyozo",
    0xBA: "Stone rubble pile",
    0xBB: "Rusted Robo",
    0xBC: "Gaspar (Gurus cutscene)",
    0xBD: "UNUSED",
    0xBE: "Orange cat",
    0xBF: "Middle Ages/Present Age villager - little boy",
    0xC0: "Middle Ages/Present Age villager - little girl",
    0xC1: "Spinning water element",
    0xC2: "Blue shining star - small",
    0xC3: "Blue shining star - large",
    0xC4: "Multiple balloons",
    0xC5: "Dancing woman (Millennial Fair ending)",
    0xC6: "Millennial Fair visitor - little girl",
    0xC7: "Silver Leene's bell",
    0xC8: "Figure atop Magus' Castle (ending)",
    0xC9: "Serving tray with drinks",
    0xCA: "THE END text",
    0xCB: "Human Glenn (ending cutscene)",
    0xCC: "Queen Zeal (Death Peak cutscene)",
    0xCD: "Schala (Death Peak cutscene)",
    0xCE: "Lavos (Death Peak cutscene)",
    0xCF: "Crono (Death Peak cutscene)",
    0xD0: "Hironobu Sakaguchi (Programmer's Ending)",
    0xD1: "Yuji Horii (Programmer's Ending)",
    0xD2: "Akira Toriyama (Programmer's Ending)",
    0xD3: "Kazuhiko Aoki (Programmer's Ending)",
    0xD4: "Lightning flash",
    0xD5: "Lara",
    0xD6: "Purple explosion",
    0xD7: "Crono's mom (Millennial Fair ending)",
    0xD8: "UNUSED",
    0xD9: "UNUSED",
    0xDA: "UNUSED",
    0xDB: "UNUSED",
    0xDC: "UNUSED",
    0xDD: "UNUSED",
    0xDE: "UNUSED",
    0xDF: "UNUSED",
    0xE0: "Green balloon/NOT USED",
    0xE1: "Yellow balloon/NOT USED",
    0xE2: "Blue balloon/NOT USED",
    0xE3: "Pink balloon/NOT USED",
    0xE4: "Brown glowing light/NOT USED",
    0xE5: "Yellow glowing light/NOT USED",
    0xE6: "Purple glowing light/NOT USED",
    0xE7: "Blue glowing light",
    0xE8: "UNUSED",
    0xE9: "UNUSED",
    0xEA: "UNUSED",
    0xEB: "UNUSED",
    0xEC: "UNUSED",
    0xED: "UNUSED",
    0xEE: "UNUSED",
    0xEF: "UNUSED",
    0xF0: "UNUSED",
    0xF1: "UNUSED",
    0xF2: "UNUSED",
    0xF3: "UNUSED",
    0xF4: "UNUSED",
    0xF5: "UNUSED",
    0xF6: "UNUSED",
    0xF7: "UNUSED",
    0xF8: "UNUSED",
    0xF9: "UNUSED",
    0xFA: "UNUSED",
    0xFB: "UNUSED",
    0xFC: "UNUSED",
    0xFD: "UNUSED",
    0xFE: "UNUSED",
    0xFF: "UNUSED",
}

enemies = {
    0x00: "Nu",
    0x01: "Reptite",
    0x02: "Terrasaur",
    0x03: "Kilwala",
    0x04: "Krawlie",
    0x05: "Hench",
    0x06: "Omicrone",
    0x07: "Martello",
    0x08: "Bellbird",
    0x09: "Panel",
    0x0A: "Mammon M.",
    0x0B: "Lavos 3rd Form",
    0x0C: "Blue Imp",
    0x0D: "Green Imp",
    0x0E: "Stone Imp",
    0x0F: "Mud Imp",
    0x10: "Roly",
    0x11: "Poly",
    0x12: "Rolypoly",
    0x13: "Roly Rider",
    0x14: "Lavos Giga Right Arm",
    0x15: "Blue Eaglet",
    0x16: "Gold Eaglet",
    0x17: "Red Eaglet",
    0x18: "Lavos Giga Left Arm",
    0x19: "Avian Chaos",
    0x1A: "Imp Ace",
    0x1B: "Bantam Imp",
    0x1C: "Gnasher",
    0x1D: "Gnawer",
    0x1E: "Nagaette",
    0x1F: "NOT USED",
    0x20: "Ruminator",
    0x21: "NOT USED",
    0x22: "Octopod",
    0x23: "Octoblush",
    0x24: "Octobino",
    0x25: "Zeal",
    0x26: "Fly Trap",
    0x27: "Meat Eater",
    0x28: "Man Eater",
    0x29: "Krakker",
    0x2A: "Egder",
    0x2B: "Defunct",
    0x2C: "Departed",
    0x2D: "Deceased",
    0x2E: "Decedent",
    0x2F: "Macabre",
    0x30: "Reaper",
    0x31: "Guard",
    0x32: "Sentry",
    0x33: "Free Lancer",
    0x34: "Outlaw",
    0x35: "Giga Mutant",
    0x36: "Giga Mutant Bottom",
    0x37: "TerraMutant",
    0x38: "TerraMutant Bottom",
    0x39: "Juggler",
    0x3A: "Retinite",
    0x3B: "Mage",
    0x3C: "NOT USED",
    0x3D: "Reptite",
    0x3E: "Blue Shield",
    0x3F: "Yodu De",
    0x40: "Incognito",
    0x41: "PeepingDoom",
    0x42: "Boss Orb",
    0x43: "Side Kick",
    0x44: "NOT USED",
    0x45: "Jinn Bottle",
    0x46: "Evilweevil",
    0x47: "Tempurite",
    0x48: "Diablos",
    0x49: "Gargoyle",
    0x4A: "Grimalkin",
    0x4B: "Hench",
    0x4C: "T'pole",
    0x4D: "Croaker",
    0x4E: "Amphibite",
    0x4F: "Bull Frog",
    0x50: "Mad Bat",
    0x51: "Vamp",
    0x52: "Scouter",
    0x53: "Flyclops",
    0x54: "Bugger",
    0x55: "Debugger",
    0x56: "Debuggest",
    0x57: "Sorcerer",
    0x58: "Jinn",
    0x59: "Barghest",
    0x5A: "NOT USED",
    0x5B: "Crater",
    0x5C: "Volcano",
    0x5D: "Shitake",
    0x5E: "Hetake",
    0x5F: "Rubble",
    0x60: "NOT USED",
    0x61: "Shist",
    0x62: "Pahoehoe",
    0x63: "Nereid",
    0x64: "Fake Save",
    0x65: "Mohavor",
    0x66: "Shadow",
    0x67: "NOT USED",
    0x68: "Base",
    0x69: "Acid",
    0x6A: "Alkaline",
    0x6B: "Ion",
    0x6C: "Anion",
    0x6D: "Thrasher",
    0x6E: "Lavos Spawn Eye",
    0x6F: "Lavos Spawn",
    0x70: "Lasher",
    0x71: "Goblin",
    0x72: "Ogre",
    0x73: "Cave Bat",
    0x74: "Ogan",
    0x75: "Flunky",
    0x76: "Groupie",
    0x77: "NOT USED",
    0x78: "NOT USED",
    0x7A: "Cave Ape",
    0x7B: "Megasaur",
    0x7C: "Omnicrone",
    0x7D: "Beast",
    0x7E: "Blue Beast",
    0x7F: "Red Beast",
    0x80: "Turret",
    0x81: "Lizardactyl",
    0x82: "Fake Nu",
    0x83: "Avian Rex",
    0x84: "Blob",
    0x85: "Alien",
    0x86: "Rat",
    0x87: "Gremlin",
    0x88: "Runner",
    0x89: "Proto 2",
    0x8A: "Proto 3",
    0x8B: "Proto 4",
    0x8C: "Bug",
    0x8D: "Beetle",
    0x8E: "Goon",
    0x8F: "Cyrus",
    0x90: "Yakra",
    0x91: "Rain Frog",
    0x92: "Gato",
    0x93: "Dragon Tank",
    0x94: "Grinder",
    0x95: "Golem",
    0x96: "Synchrite",
    0x97: "Masa",
    0x98: "Mune",
    0x99: "Masa & Mune",
    0x9A: "Azala",
    0x9B: "Nizbel",
    0x9C: "Nizbel II",
    0x9D: "Slash",
    0x9E: "Slash",
    0x9F: "Flea",
    0xA0: "Flea Plus",
    0xA1: "Dalton",
    0xA2: "Dalton Plus",
    0xA3: "Mutant",
    0xA4: "Metal Mute",
    0xA5: "Super Slash",
    0xA6: "Ozzie",
    0xA7: "Ozzie",
    0xA8: "Great Ozzie",
    0xA9: "Heckran",
    0xAA: "Gigasaur",
    0xAB: "Leaper",
    0xAC: "Fossil Ape",
    0xAD: "Tank Head",
    0xAE: "Frog King",
    0xAF: "Octorider",
    0xB0: "Zeal",
    0xB1: "Zeal Right Hand",
    0xB2: "Zeal Left Hand",
    0xB3: "Zombor",
    0xB4: "Zombor Upper Half",
    0xB5: "Retinite Bottom Half",
    0xB6: "Retinite Upper Half",
    0xB7: "Display",
    0xB8: "Mega Mutant",
    0xB9: "Mega Mutant Bottom Half",
    0xBA: "Super Slash",
    0xBB: "Flea Plus",
    0xBC: "BlackTyrano",
    0xBD: "RustTyrano",
    0xBE: "MotherBrain",
    0xBF: "MotherBrain Body",
    0xC0: "Atropos XR",
    0xC1: "Cybot",
    0xC2: "Lavos",
    0xC3: "Lavos",
    0xC4: "Lavos",
    0xC5: "Lavos",
    0xC6: "Lavos",
    0xC7: "Yakra XIII",
    0xC8: "Tubster",
    0xC9: "Lavos",
    0xCA: "Lavos",
    0xCB: "Lavos 2nd Form",
    0xCC: "Lavos 2nd Form Left Arm",
    0xCD: "Lavos 2nd Form Right Arm",
    0xCE: "Lavos Core",
    0xCF: "Bit",
    0xD0: "Byte",
    0xD1: "Giga Gaia",
    0xD2: "Giga Gaia Left Arm",
    0xD3: "Giga Gaia Right Arm",
    0xD4: "Guardian",
    0xD5: "Red Scout",
    0xD6: "Blue Scout",
    0xD7: "Lavos Spawn",
    0xD8: "Lavos Spawn Eye",
    0xD9: "Laser Guard",
    0xDA: "Lavos Dragon Tank Left",
    0xDB: "Lavos Dragon Tank Right",
    0xDC: "Lavos Guardian Left",
    0xDD: "Lavos Guardian Right",
    0xDE: "Lavos Zombor Lower",
    0xDF: "Lavos BlackTyranno",
    0xE0: "Spekkio Frog",
    0xE1: "Spekkio Kilwala",
    0xE2: "Spekkio Ogre",
    0xE3: "Spekkio Omnicrone",
    0xE4: "Spekkio Masa & Mune",
    0xE5: "Spekkio Nu",
    0xE6: "Lavos BlackTyranno",
    0xE7: "Lavos GigaGaia",
    0xE8: "Lavos NOT USED",
    0xE9: "Lavos NOT USED",
    0xEA: "Lavos NOT USED",
    0xEB: "Lavos 1st form before",
    0xEC: "Lavos 1st form after",
    0xED: "Lavos 3rd form left bit",
    0xEE: "Hexapod",
    0xEF: "Lavos 3rd form right bit",
    0xF0: "Flea?",
    0xF1: "Chains",
    0xF2: "Roly Bomber",
    0xF3: "Golem Boss",
    0xF4: "Johnny",
    0xF5: "Basher",
    0xF6: "Son of Sun",
    0xF7: "Son of Sun Flame",
    0xF8: "R Series",
    0xF9: "Magus",
    0xFA: "Magus",
    0xFB: "NOT USED",
    0xFC: "NOT USED",
    0xFD: "NOT USED",
    0xFE: "NOT USED",
    0xFF: "NOT USED",
}

known_mem_locations = {
    0x7E0005: "PrevLocation",
    0x7E0010: "DisableMenu",
    0x7E0011: "DisablePause",
    0x7E0051: "JoyPress",
    0x7E00D9: "TempNum",
    0x7E00F8: "RandomNumSeed",
    0x7E00FA: "BattleMusic",
    0x7E00FB: "TreasureChestSnd",
    0x7E00FC: "DoorOpenSnd",
    0x7E017C: "OWAction",
    0x7E0190: "EpochLoXCoord",
    0x7E0191: "EpochHiXCoord",
    0x7E0192: "EpochLoYCoord",
    0x7E0193: "EpochHiYCoord",
    0x7E0194: "EpochStatus",
    0x7E019A: "DactylXCoord",
    0x7E019C: "DactylYCoord",
    0x7E019E: "DactylStatus",
    0x7E019F: "EpochMapLoc.LowVal",
    0x7E01A0: "EpochMapLoc.HighVal",
    0x7E1E2B: "OverworldMusic0",
    0x7E1E2C: "OverworldMusic1",
    0x7E1E2D: "OverworldMusic2",
    0x7E1E2E: "OverworldMusic3",
    0x7E1E2F: "OverworldMusic4",
    0x7E1E30: "OverworldMusic5",
    0x7E1E31: "OverworldMusic6",
    0x7E1E32: "OverworldMusic7",
    0x7E1E36: "StorylineCtr",
    0x7E1E87: "OverworldYearBoxTimer",
    0x7E2812: "CronoLevel",
    0x7E2862: "MarleLevel",
    0x7E28B2: "LuccaLevel",
    0x7E2902: "RoboLevel",
    0x7E2952: "FrogLevel",
    0x7E29A2: "AylaLevel",
    0x7E29F2: "MagusLevel",
    0x7E2980: "PC1",
    0x7E2981: "PC2",
    0x7E2982: "PC3",
    0x7E2C23: "PCNames",
    0x7E2C53: "Gold",
    0x7F0000: "StorylineCtr",
    0x7F0050: "CourtFlags",
    0x7F0051: "InnocentVotes",
    0x7F0052: "SilverPoints",
    0x7F0053: "Kittens",
    0x7F0054: "FairFlags",
    0x7F0055: "MarleFlags",
    0x7F0056: "TelepodFlags",
    0x7F005A: "LuccaFlags",
    0x7F005D: "PoyozoCatPrizes",
    0x7F005E: "ClonePrizes",
    0x7F005F: "CatFood",
    0x7F0061: "SavesCreated",
    0x7F006D: "EndingAndMelchiorFlags",
    0x7F0150: "MomFlags",
    0x7F0152: "MiscFlags",
    0x7F015F: "ClonePermissionFlags",
    0x7F01EF: "CharacterLock",
    0x7F01FC: "LastBattleStatus",
    0x7F01FD: "KeepCurSong",
    0x7E0100: "CurrLocation",
    0x7E0102: "Starting X Coord",
    0x7E0103: "Starting Y Coord",
    0x7E0104: "Starting facing",
    0x7E0120: "WalkThroughWalls",
    0x7E012A: "CurrStringIndex",
    0x7E012B: "CurrStringIndexB8",
    0x7E0158: "IdleTime",
    0x7E016D: "CurrObjID",
    0x7E0197: "PC1ObjNum",
    0x7E0199: "PC2ObjNum",
    0x7E019B: "PC3ObjNum",
    0x7E01BD: "TotalObjects",
    0x7E01DF: "Mode7Index",
    0x7E020D: "CurrStringIndex",
    0x7E0283: "PC1 X Coord",
    0x7E0285: "PC1 Y Coord",
    0x7E0294: "EpochObtained",
    0x7E029E: "DactylsObtained",
    0x7E02AE: "CurrSong",
    0x7E0400: "Gametime",
    0x7E0F00: "Byte 1: Object draw status Byte 2: Object current animation frame",
    0x7E1100: "Byte 1: Object type Byte 2: Object LoadPC/NPC/Enemy index",
    0x7E1200: "Byte 1: Object pointer to PC/NPC Enemy graphics (bank), Byte 2: Sprite size value from 24F000 sprite data",
    0x7E1280: "Object pointer to PC/NPC Enemy graphics (2 bytes)",
    0x7E1300: "Byte 1: Object pointer to sprite assembly (bank), Byte 2: Unknown",
    0x7E1380: "Object pointer to sprite assembly (2 bytes)",
    0x7E1B00: "Byte 1: Object unknown, Byte 2: Object solidity props. (Event Command 84)",
    0x7E1B58: "Index of location name on overworld map",
    0x7E1C00: "Byte 1: Object priority, Byte 2: Object activate status (Event Command 08/09)",
    0x7E1C80: "Byte 1: Object move props. (Event Command 0D), Byte 2: Object tile position props. (Event Command 0E)",
    0x7E21A2: "PC1 palette",
    0x7E21C2: "PC2 palette",
    0x7E21E2: "PC3 palette",
    0x7E2400: "Inventory item",
    0x7E2500: "Inventory quantity",
    0x7E2600: "Crono Portrait",
    0x7E2603: "Crono current HP",
    0x7E2605: "Crono max HP",
    0x7E2607: "Crono current MP",
    0x7E2609: "Crono max MP",
    0x7E260B: "Crono power",
    0x7E260C: "Crono stamina",
    0x7E260D: "Crono speed",
    0x7E260E: "Crono magic",
    0x7E260F: "Crono hit",
    0x7E2610: "Crono evade",
    0x7E2611: "Crono magic defense",
    0x7E2612: "Crono Level",
    0x7E2613: "Crono XP",
    0x7E2627: "Crono Helmet Equipped",
    0x7E2628: "Crono Armor Equipped",
    0x7E2629: "Crono Weapon Equipped",
    0x7E262A: "Crono Accessory Equipped",
    0x7E262B: "Crono Exp Next",
    0x7E262D: "Crono Skill Points Needed To Gain Next Tech",
    0x7E2650: "Marle's Data",
    0x7E26A0: "Lucca's Data",
    0x7E26F0: "Robo's Data",
    0x7E2740: "Frog's Data",
    0x7E2790: "Ayla's Data",
    0x7E27E0: "Magus's Data",
    0x7E2830: "Tech to learn next (1 byte per PC)",
    0x7E2837: "Single Techs learned (1 byte per PC)",
    0x7E283E: "Crono Marle Double Techs learned",
    0x7E283F: "Crono Lucca Double Techs learned",
    0x7E2840: "Crono Robo Double Techs learned",
    0x7E2841: "Crono Frog Double Techs learned",
    0x7E2842: "Crono Ayla Double Techs learned",
    0x7E2843: "Marle Lucca Double Techs learned",
    0x7E2844: "Marle Robo Double Techs learned",
    0x7E2845: "Marle Frog Double Techs learned",
    0x7E2846: "Marle Ayla Double Techs learned",
    0x7E2847: "Lucca Robo Double Techs learned",
    0x7E2848: "Lucca Ayla Double Techs learned",
    0x7E2849: "Robo Frog Double Techs learned",
    0x7E284A: "Robo Ayla Double Techs learned",
    0x7E284B: "Frog Ayla Double Techs learned",
    0x7E284C: "Lucca Frog Double Techs learned",
    0x7E284D: "Delta Force - Crono Marle Lucca Triple Tech",
    0x7E284E: "Lifeline - Crono Marle Robo Triple Tech",
    0x7E284F: "Arc Impulse - Crono Marle Frog Triple Tech",
    0x7E2850: "Final Kick - Crono Marle Ayla Triple Tech",
    0x7E2851: "Fire Zone - Crono Lucca Robo Triple Tech",
    0x7E2852: "Delta Storm - Crono Lucca Frog Triple Tech",
    0x7E2853: "GatlingKick - Crono Lucca Ayla Triple Tech",
    0x7E2854: "Triple Raid - Crono Robo Frog Triple Tech",
    0x7E2855: "Twister - Crono Robo Ayla Triple Tech",
    0x7E2856: "3D Attack - Crono Frog Ayla Triple Tech",
    0x7E2857: "DarkEternal (Black Rock) - Marle Lucca Magu",
    0x7E2858: "Omega Flare (Blue Rock) - Lucca Robo Magus",
    0x7E2859: "Spin Strike (SilverRock) - Robo Frog Ayla",
    0x7E285A: "PoyozoDance (White Rock) - Marle Lucca Ayla",
    0x7E285B: "Grand Dream (Gold Rock) - Marle Frog Robo",
    0x7E285C: "All $FF, copied from 0C025C-0C0261, unused?",
    0x7E2862: "JUNK, Weapon Stats copied from 0C0262-0C027",
    0x7E2880: "Appears to be unused space (included in SRA",
    0x7E2980: "PC1",
    0x7E2981: "PC2",
    0x7E2982: "PC3",
    0x7E2983: "Reserve PC1",
    0x7E2984: "Reserve PC2",
    0x7E2985: "Reserve PC3",
    0x7E2986: "Reserve PC4",
    0x7E2987: "Reserve PC5",
    0x7E2988: "Reserve PC6",
    0x7E2989: "Event Command D8 settings byte 1",
    0x7E299C: "Number of times the game has been saved",
    0x7E299E: "Copied from 307FE1 in SRAM, total times a n",
    0x7E299F: "Unknown, related to new game ATB menu and c",
    0x7E29AC: "Attract mode battle data to use next - $00",
    0x7E29AE: "Currently playing song (Location)",
    0x7E29AF: "Characters who have joined your party",
    0x7E2A1F: "Event Command D8 settings byte 2",
    0x7E2A21: "Used for several regular and boss battles, unknown purpose",
    0x7E3000: "Layer 1 Tile",
    0x7E3040: "Layer 2 Tile",
    0x7E3080: "Layer 3 Tile",
    0x7E30C0: "Tile Properties 1",
    0x7E3100: "Repeat of previous pattern for each row",
    0x7E4000: "L2 Tiles",
    0x7E5800: "L1 Tiles",
    0x7E5EBA: "Ayla's battle speed (PC2 maybe?)",
    0x7E7000: "Tile properties",
    0x7E7040: "Tile Properties 3",
    0x7E7080: "???",
    0x7E7100: "Repeat of previous pattern for each row",
    0x7E7200: "Music transition data",
    0x7E7E00: "Exits",
    0x7EAE93: "Current tech animation [Crono]",
    0x7EAFAB: "Character 1 attack bar value",
    0x7EAFAC: "Character 2 attack bar value",
    0x7EAFAD: "Character 3 attack bar value",
    0x7F0051: "Trial innocent votes",
    0x7F0053: "Kittens",
    0x7F005F: "CatFood",
    0x7F006E: "Result used for Beyond Time / Reunion ending, Successor of Guardia ending",
    0x7F007C: "Lara loses her legs",
    0x7F00E1: "Beat Spekkio E5",
    0x7F00E2: "Spekkio has met Magus",
    0x7F00F7: "Told sapling woman to plant the tree",
    0x7F00FE: "Naga-ette Bromide obtained",
    0x7F013A: "Fought Son of Sun",
    0x7F0140: "Mom has met Magus",
    0x7F014A: "Power Tab in long Geno Dome hallway",
    0x7F014E: "Mother speaks to PCs in long Geno Dome hallway",
    0x7F0190: "Brought to Prison",
    0x7F0198: "Defeated Guards in Prison Supervisor's Office",
    0x7F01A2: "Fought Medina Merchant",
    0x7F01CF: "Saving available",
    0x7F01D2: "Gave Jerky away",
    0x7F01DF: "Character lock status",
    0x7F01E0: "Spekkio has given Magus magic",
    0x7F01EC: "Status of last battle fought 00 - You won/ran away, 01 - defeated",
    0x7F01ED: "Keep Current Song flag - 00 off, 01 on",
    0x7F01F0: "Location storyline flags",
    0x7F01F7: "Black Omen has appeared",
    0x7F0A80: "Event result byte",
    0x7F0B00: "Byte 1: Unknown, Byte 2: Object animation loops left (Event Command B7)",
}

items = {
    0x00: "Empty",
    0x01: "Wood Sword",
    0x02: "Iron Blade",
    0x03: "SteelSaber",
    0x04: "Lode Sword",
    0x05: "Red Katana",
    0x06: "Flint Edge",
    0x07: "Dark Saber",
    0x08: "Aeon Blade",
    0x09: "Demon Edge",
    0x0A: "AlloyBlade",
    0x0B: "Star Sword",
    0x0C: "VedicBlade",
    0x0D: "Kali Blade",
    0x0E: "Shiva Edge",
    0x0F: "Bolt Sword",
    0x10: "Slasher",
    0x11: "Bronze Bow",
    0x12: "Iron Bow",
    0x13: "Lode Bow",
    0x14: "Robin Bow",
    0x15: "Sage Bow",
    0x16: "Dream Bow",
    0x17: "CometArrow",
    0x18: "SonicArrow",
    0x19: "Valkerye",
    0x1A: "Siren",
    0x1F: "Air Gun",
    0x20: "Dart Gun",
    0x21: "Auto Gun",
    0x22: "PicoMagnum",
    0x23: "Plasma Gun",
    0x24: "Ruby Gun",
    0x25: "Dream Gun",
    0x26: "MegaBlast",
    0x27: "Shock Wave",
    0x28: "WonderShot",
    0x29: "Graedus",
    0x2E: "Tin Arm",
    0x2F: "Hammer Arm",
    0x30: "MirageHand",
    0x31: "Stone Arm",
    0x32: "DoomFinger",
    0x33: "Magma Hand",
    0x34: "MegatonArm",
    0x35: "Big Hand",
    0x36: "Kaiser Arm",
    0x37: "Giga Arm",
    0x38: "Terra Arm",
    0x39: "Crisis Arm",
    0x3B: "BronzeEdge",
    0x3C: "Iron Sword",
    0x3D: "Masamune (1st)",
    0x3E: "FlashBlade",
    0x3F: "Pearl Edge",
    0x40: "Rune Blade",
    0x41: "BraveSword",
    0x42: "Masamune (2nd)",
    0x43: "Demon Hit",
    0x44: "Fist ",
    0x47: "Iron Fist",
    0x48: "BronzeFist",
    0x4B: "DarkScythe",
    0x4C: "Hurricane",
    0x4D: "StarScythe",
    0x4E: "DoomSickle",
    0x4F: "Mop",
    0x50: "Bent Sword",
    0x51: "Bent Hilt",
    0x52: "Masamune (0 attack)",
    0x53: "Swallow ",
    0x54: "Slasher 2",
    0x55: "Rainbow",
    0x5B: "Hide Tunic",
    0x5C: "Karate Gi",
    0x5D: "BronzeMail",
    0x5E: "MaidenSuit",
    0x5F: "Iron Suit",
    0x60: "Titan Vest",
    0x61: "Gold Suit",
    0x62: "Ruby Vest",
    0x63: "Dark Mail",
    0x64: "Mist Robe",
    0x65: "Meso Mail",
    0x66: "Lumin Robe",
    0x67: "Flash Mail",
    0x68: "Lode Vest",
    0x69: "Aeon Suit",
    0x6A: "ZodiacCape",
    0x6B: "Nova Armor",
    0x6C: "PrismDress",
    0x6D: "Moon Armor",
    0x6E: "Ruby Armor",
    0x6F: "RavenArmor",
    0x70: "Gloom Cape",
    0x71: "White Mail",
    0x72: "Black Mail",
    0x73: "Blue Mail",
    0x74: "Red Mail",
    0x75: "White Vest",
    0x76: "Black Vest",
    0x77: "Blue Vest",
    0x78: "Red Vest",
    0x79: "Taban Vest",
    0x7A: "Tabam Suit",
    0x7C: "Hide Cap",
    0x7D: "BronzeHelm",
    0x7E: "Iron Helm",
    0x7F: "Beret",
    0x80: "Gold Helm",
    0x81: "Rock Helm",
    0x82: "CeraTopper",
    0x83: "Glow Helm",
    0x84: "Lode Helm",
    0x85: "Aeon Helm",
    0x86: "Prism Helm",
    0x87: "Doom Helm",
    0x88: "Dark Helm",
    0x89: "Gloom Helm",
    0x8A: "Safe Helm",
    0x8B: "Taban Helm",
    0x8C: "Sight Cap",
    0x8D: "Memory Cap",
    0x8E: "Time Hat",
    0x8F: "vigil Hat",
    0x90: "OzziePants",
    0x91: "Haste Helm",
    0x92: "R'bow Helm",
    0x93: "MermaidCap",
    0x95: "Bandana",
    0x96: "Ribbon",
    0x97: "PowerGlove",
    0x98: "Defender",
    0x99: "MagicScarf",
    0x9A: "Amulet",
    0x9B: "Dash Ring",
    0x9C: "Hit Ring",
    0x9D: "Power Ring",
    0x9E: "Magic Ring",
    0x9F: "Wall Ring",
    0xA0: "SilverErng",
    0xA1: "Gold Erng",
    0xA2: "SilverStud",
    0xA3: "Gold Stud",
    0xA4: "SightScope",
    0xA5: "Charm Top",
    0xA6: "Rage Band",
    0xA7: "FrenzyBand",
    0xA8: "Third Eye",
    0xA9: "Wallet",
    0xAA: "GreenDream",
    0xAB: "Berserker",
    0xAC: "PowerScarf",
    0xAD: "Speed Belt",
    0xAE: "Black Rock",
    0xAF: "Blue Rock",
    0xB0: "SilverRock",
    0xB1: "White Rock",
    0xB2: "Gold Rock",
    0xB3: "Hero Medal",
    0xB4: "MuscleRing",
    0xB5: "Flea Vest",
    0xB6: "Magic Seal",
    0xB7: "Power Seal",
    0xB8: "Relic",
    0xB9: "SeraphSong",
    0xBA: "Sun Shades",
    0xBB: "PrismSpecs",
    0xBD: "Tonic",
    0xBE: "Mid Tonic",
    0xBF: "Full Tonic",
    0xC0: "Ether",
    0xC1: "Mid Ether",
    0xC2: "Full Ether",
    0xC3: "Elixer",
    0xC4: "HyperEther",
    0xC5: "MegaElixer",
    0xC6: "Heal",
    0xC7: "Revive",
    0xC8: "Shelter",
    0xC9: "Power Meal",
    0xCA: "Lapis",
    0xCB: "Barrier",
    0xCC: "Shield",
    0xCD: "Power Tab",
    0xCE: "Magic Tab",
    0xCF: "Speed Tab",
    0xD0: "Petal",
    0xD1: "Fang",
    0xD2: "Horn",
    0xD3: "Feather",
    0xD4: "Seed",
    0xD5: "Bike Key",
    0xD6: "Pendant",
    0xD7: "Gate Key",
    0xD8: "PrismShard",
    0xD9: "C. Trigger",
    0xDA: "Tools",
    0xDB: "Jerky",
    0xDC: "Dreamstone",
    0xDD: "Race Log",
    0xDE: "Moon Stone",
    0xDF: "Sun Stone",
    0xE0: "Ruby Knife",
    0xE1: "Yakra Key",
    0xE2: "Clone",
    0xE3: "Toma's Pop",
    0xE4: "2 Petals",
    0xE5: "2 Fangs",
    0xE6: "2 Horns",
    0xE7: "2 Feathers",
}

storyline = {
    0x00: "New Game",
    0x03: "Crono gets out of bed",
    0x06: "Marle has lost her pendant",
    0x08: "Marle has joined Crono at the fair",
    0x0A: "Visited Lucca's Telepod exhibit",
    0x0C: "Marle disappeared into portal",
    0x0F: "Met Marle as Queen Leene",
    0x10: "Marle disappears in castle",
    0x12: "Lucca arrives in past",
    0x15: "Unmasked the nuns at the Cathedral",
    0x1B: "Rescued Queen Leene",
    0x1C: "Frog leaves Guardia throneroom",
    0x21: "Marle rematerializes",
    0x24: "Lucca opens the gate back to the present",
    0x27: "Arrived back in the present",
    0x2A: "Detained for trial",
    0x2D: "Trial ends",
    0x2E: "Lucca comes to break Crono out of prison",
    0x30: "Escape Guardia Castle",
    0x33: "Escape through Guardia Forest Portal",
    0x34: "Met the people of Arris Dome",
    0x35: "Exploring the lower levels of Arris Dome",
    0x36: "Discovered visual record of Day of Lavos",
    0x37: "Given seeds to people of Arris Dome",
    0x3C: "Setting out for the Factory Ruins",
    0x3F: "Security system goes haywire",
    0x40: "Robo got creamed",
    0x42: "Defeated R Series",
    0x45: "Decided to leave via the Proto Dome portal",
    0x48: "Arrived at the End of Time",
    0x49: "Spoken to Gaspar",
    0x4A: "Gaspar calls when trying to leave the first time",
    0x4B: "Gaspar says to take a look in the room behind him",
    0x4C: "Spekkio",
    0x4D: "Learned magic",
    0x4E: "Arrive in Medina",
    0x51: "Defeated Heckran",
    0x54: "Arrive in 600 AD to search for Magus",
    0x57: "Ozzie launches an attack on Zenan Bridge",
    0x5A: "Ozzie summons Zombor",
    0x5D: "Met Tata on Denadoro Mts.",
    0x60: "Received Bent Sword",
    0x66: "Received Hero's Medal",
    0x69: "Received Bent Hilt",
    0x6C: "Showed Melchior the broken Masamune",
    0x6F: "Met Ayla",
    0x72: "Win soup race",
    0x75: "Awaken without Gate Key",
    0x78: "Setting out to find Gate Key",
    0x7B: "Find Kino in Forest Maze",
    0x7C: "Defeated Nizbel",
    0x7D: "Leaving Chief's Hut to return to the portal",
    0x7E: "Leaving Prehistoric times with Dreamstone",
    0x81: "Melchior reforges the Masamune",
    0x84: "Frog decides to face Magus",
    0x87: "Opened the Magic Cave",
    0x88: "Arrived at Castle Magus",
    0x89: "Ozzie Defeated",
    0x8A: "Magus Defeated",
    0x8D: "Arrive in Prehistoric times from Castle Magus Inner Sanctum",
    0x8E: "Arrive at Laruba",
    0x90: "Meet Ayla at Dactyl Nest Summit",
    0x93: "Setting out for Tyrano Lair",
    0x96: "Defeated Reptite guards outside of Kino's cell",
    0x97: "Kino freed",
    0x98: "Kino opens fossil head",
    0x99: "Lavos falls to Earth",
    0x9F: "Traveled to 12000 BC for first time",
    0xA2: "Watched Schala open door to Zeal throneroom",
    0xA5: "Charged pendant",
    0xA8: "Captured by Dalton",
    0xAB: "Locked out of 12000 BC",
    0xAE: "Acquired Epoch",
    0xB1: "Unused - Guru on Mt Woe",
    0xB4: "Fight the Mud Imp and his beasts",
    0xB7: "Mt Woe falls",
    0xBA: "Dalton kidnaps Schala",
    0xBB: "Melchior gives Crono the Ruby Knife",
    0xBD: "Defeated Dalton in Zeal throneroom",
    0xC3: "Queen demands Schala to raise power of Mammon Machine",
    0xC6: "Queen anticipates immortality nearing",
    0xC9: "Defeated GolemTwins",
    0xCB: "Crono gets whacked",
    0xCC: "Tidal Wave washes over land",
    0xCD: "Awaken in Last Village",
    0xCF: "Dalton attacks Last Village",
    0xD2: "Blackbird crashes",
    0xD3: "Met Magus at North Cape",
    0xD4: "Black Omen rises",
    0xD5: "Received the Time Egg",
    0xD6: "Destroyed the Black Omen",
}

music = {
    0x00: "Silence",
    0x01: "1.05 - Memories of Green",
    0x02: "1.09 - Wind Scene",
    0x03: "3.04 - Corridors of Time",
    0x04: "2.20 - Rhythm of Wind, Sky, and Earth",
    0x05: "2.01 - Ruined World",
    0x06: "1.06 - Guardia Millenial Fair",
    0x07: "3.09 - Far Off Promise",
    0x08: "1.11 - Secret of the Forest",
    0x09: "3.05 - Zeal Palace",
    0x0A: "2.10 - Remains of Factory",
    0x0B: "2.19 - Ayla's Theme",
    0x0C: "1.13 - Courage and Pride",
    0x0D: "2.05 - Lavos' Theme",
    0x0E: "2.09 - Robo's Theme",
    0x0F: "1.03 - Morning Sunlight",
    0x10: "1.15 - Manoria Cathedral",
    0x11: "Sounds of the Ocean",
    0x12: "Leene's Bell",
    0x13: "3.10 - Wings that Cross Time",
    0x14: "3.06 - Schala's Theme",
    0x15: "2.14 - Delightful Spekkio",
    0x16: "1.23 - A Shot of Crisis",
    0x17: "1.21 - Kingdom Trial",
    0x18: "1.02 - Chrono Trigger",
    0x19: "Blackbird Interior",
    0x1A: "Blackbird Exterior",
    0x1B: "1.20 - Fanfare 1",
    0x1C: "2.12 - Fanfare 2",
    0x1D: "3.03 - At the Bottom of the Night",
    0x1E: "1.04 - Peaceful Day",
    0x1F: "1.08 - A Strange Happening",
    0x20: "Dungeon dripping noise",
    0x21: "Running Water",
    0x22: "Wind",
    0x23: "1.22 - The Hidden Truth",
    0x24: "1.16 - A Prayer to the Road that Leads",
    0x25: "1.14 - Huh?",
    0x26: "2.06 - The Day the World Revived",
    0x27: "2.07 - Robo Gang Johnny",
    0x28: "2.24 - Battle with Magus",
    0x29: "1.18 - Boss Battle 1",
    0x2A: "1.19 - Frog's Theme",
    0x2B: "1.10 - Goodnight",
    0x2C: "2.08 - Bike Chase",
    0x2D: "2.04 - People who Threw Away the Will to Live",
    0x2E: "2.02 - Mystery of the Past",
    0x2F: "2.16 - Underground Sewer",
    0x30: "1.01 - Presentiment",
    0x31: "3.08 - Undersea Palace",
    0x32: "3.14 - Last Battle",
    0x33: "2.03 - Lab 16's Ruins",
    0x34: "Inside the Shell",
    0x35: "Quake",
    0x36: "2.21 - Burn!  Bobonga!",
    0x37: "Wormhole",
    0x38: "2.18 - Primitive Mountain",
    0x39: "3.13 - World Revolution",
    0x3A: "Lavos Scream",
    0x3B: "3.07 - Sealed Door",
    0x3C: "1.17 - Silent Light",
    0x3D: "2.15 - Fanfare 3",
    0x3E: "2.13 - The Brink of Time",
    0x3F: "3.17 - To Far Away Times",
    0x40: "2.23 - Confusing Melody",
    0x41: "Hail Magus",
    0x42: "1.07 - Gonzales' Song",
    0x43: "Underground River, Rain",
    0x44: "3.11 - Black Dream",
    0x45: "1.12 - Battle 1",
    0x46: "3.02 - Tyran Castle",
    0x47: "Tsunami",
    0x48: "2.22 - Magus' Castle",
    0x49: "3.15 - First Festival of Stars",
    0x4A: "The Destruction of Zeal",
    0x4B: "Ocean Tide",
    0x4C: "Lavos' Breath",
    0x4D: "3.16 - Epilogue - To Good Friends",
    0x4E: "2.17 - Boss Battle 2",
    0x4F: "Fanfare 4",
    0x50: "3.12 - Determination"
}

sounds = {
    0x00: "Cursor selection",
    0x01: "Invalid cursor selection",
    0x02: "Falling sprite",
    0x03: "Pendant reacting",
    0x04: "Received item",
    0x05: "Activating portal",
    0x06: "HP/MP restored",
    0x07: "End of Time HP/MP restore bucket",
    0x08: "Weapon readied",
    0x09: "Pendant reacting to Zeal throne room door",
    0x0A: "Flying object",
    0x0B: "Save point",
    0x0C: "UNUSED",
    0x0D: "UNUSED",
    0x0E: "UNUSED",
    0x0F: "UNUSED",
    0x10: "UNUSED",
    0x11: "UNUSED",
    0x12: "UNUSED",
    0x13: "UNUSED",
    0x14: "UNUSED",
    0x15: "UNUSED",
    0x16: "UNUSED",
    0x17: "UNUSED",
    0x18: "UNUSED",
    0x19: "UNUSED",
    0x1A: "UNUSED",
    0x1B: "UNUSED",
    0x1C: "UNUSED",
    0x1D: "UNUSED",
    0x1E: "UNUSED",
    0x1F: "UNUSED",
    0x20: "UNUSED",
    0x21: "UNUSED",
    0x22: "UNUSED",
    0x23: "UNUSED",
    0x24: "UNUSED",
    0x25: "UNUSED",
    0x26: "UNUSED",
    0x27: "UNUSED",
    0x28: "UNUSED",
    0x29: "UNUSED",
    0x2A: "UNUSED",
    0x2B: "UNUSED",
    0x2C: "UNUSED",
    0x2D: "UNUSED",
    0x2E: "UNUSED",
    0x2F: "UNUSED",
    0x30: "UNUSED",
    0x31: "UNUSED",
    0x32: "UNUSED",
    0x33: "UNUSED",
    0x34: "UNUSED",
    0x35: "UNUSED",
    0x36: "UNUSED",
    0x37: "UNUSED",
    0x38: "UNUSED",
    0x39: "UNUSED",
    0x3A: "UNUSED",
    0x3B: "UNUSED",
    0x3C: "UNUSED",
    0x3D: "UNUSED",
    0x3E: "UNUSED",
    0x3F: "Nothing",
    0x40: "Curtains",
    0x41: "Wind [LOOPS]",
    0x42: "Machine engine [LOOPS]",
    0x43: "PC/NPC KO'd",
    0x44: "Machine powering up [LOOPS]",
    0x45: "Leene Square fireworks on 1000 A.D. map - REQUIRES SONG 11",
    0x46: "Ocean waves [LOOPS]",
    0x47: "Bats flying [LOOPS]",
    0x48: "Frog catches Gold Rock",
    0x49: "Long explosions",
    0x4A: "Stomach growling",
    0x4B: "Computer screen error [LOOPS]",
    0x4C: "Ferry horn",
    0x4D: "Enemy surprises party",
    0x4E: "Cat meow",
    0x4F: "Long fall",
    0x50: "Heavy sirens [LOOPS]",
    0x51: "Sealed door opening",
    0x52: "Switch pressed",
    0x53: "Door opened",
    0x54: "Earthquake/rumbling [LOOPS]",
    0x55: "Gold received",
    0x56: "Giant doors opened",
    0x57: "Metal mug put down",
    0x58: "Unknown [LOOPS] - NOT USED IN EVENTS",
    0x59: "Metal objects colliding 1 ",
    0x5A: "Metal objects colliding 2",
    0x5B: "Magic Urn enemy",
    0x5C: "Exhaust",
    0x5D: "Unknown [LOOPS] - NOT USED IN EVENTS",
    0x5E: "Conveyor belt [LOOPS]",
    0x5F: "Frog versus Magus battle",
    0x60: "Metal gate crashing",
    0x61: "Squeak",
    0x62: "Running [LOOPS]",
    0x63: "Weapon readied",
    0x64: "Poly rolling [LOOPS]",
    0x65: "Treasure chest opened",
    0x66: "Carpenter's tools",
    0x67: "Invalid password entry",
    0x68: "Crane password prompt",
    0x69: "Dactyl flying [LOOPS]",
    0x6A: "Cup clang",
    0x6B: "Evil laugh",
    0x6C: "Machine malfunction [LOOPS]",
    0x6D: "Elevator moving [LOOPS]",
    0x6E: "Frog croak",
    0x6F: "Enemy scream 1",
    0x70: "Portal opening/closing",
    0x71: "Moving machine [LOOPS]",
    0x72: "Guardia Knight attack",
    0x73: "Enemy scream 2",
    0x74: "Pathway opens",
    0x75: "Unknown [LOOPS] - NOT USED IN EVENTS",
    0x76: "Unknown - NOT USED IN EVENTS",
    0x77: "Big explosion",
    0x78: "Teleport",
    0x79: "Monster snarl",
    0x7A: "NPC scream",
    0x7B: "Lightning on 2300 A.D. map",
    0x7C: "Thunder on 2300 A.D. map",
    0x7D: "Ground cracking before Lavos battle",
    0x7E: "Gavel strike - REQUIRES SONG 17",
    0x7F: "Prisoner sigh",
    0x80: "Rooster",
    0x81: "Lucca shoots Guard",
    0x82: "Metal bars rattling",
    0x83: "Guard KO'd",
    0x84: "Bushes/trees rustling",
    0x85: "Forest Ruins pyramid breaking [LOOPS]",
    0x86: "Telepod powering up [LOOPS]",
    0x87: "Sword slice",
    0x88: "Object powering up [LOOPS]",
    0x89: "Transformation",
    0x8A: "Unknown - NOT USED IN EVENTS",
    0x8B: "Slice",
    0x8C: "Crashing metal",
    0x8D: "Sprite lands",
    0x8E: "Collision",
    0x8F: "Bat squeak",
    0x90: "Enemy scream 3",
    0x91: "Imp Ace flying",
    0x92: "Dragon Tank moving [LOOPS]",
    0x93: "Ghosts [LOOPS]",
    0x94: "Sewer bridge extending",
    0x95: "Giant doors rumbling",
    0x96: "Bike race countdown",
    0x97: "Countdown start signal",
    0x98: "Robot noise",
    0x99: "Multiple explosions",
    0x9A: "Explosion",
    0x9B: "Ringing [LOOPS]",
    0x9C: "Enertron",
    0x9D: "Bones rattling",
    0x9E: "Computer display power on",
    0x9F: "Computer display power off",
    0xA0: "Typing [LOOPS]",
    0xA1: "Light sirens [LOOPS]",
    0xA2: "Retinite moving [LOOPS]",
    0xA3: "Orb enemy blinking",
    0xA4: "Enemy scream 4",
    0xA5: "Trial audience cheers",
    0xA6: "Trial audience boos",
    0xA7: "Enemy sleeping [LOOPS]",
    0xA8: "Pop",
    0xA9: "Powerful sword swing",
    0xAA: "Enemy startled",
    0xAB: "Water splash",
    0xAC: "Epoch preparing to warp",
    0xAD: "Epoch time warps",
    0xAE: "Epoch powering down",
    0xAF: "Epoch powering up 1 [LOOPS]",
    0xB0: "Tonic obtained",
    0xB1: "Laughing",
    0xB2: "Lavos spawn scream",
    0xB3: "Crono obtains magic",
    0xB4: "Soldier walking [LOOPS]",
    0xB5: "Parried attack",
    0xB6: "Scout enemies appear",
    0xB7: "Hyper Kabob cooking",
    0xB8: "Digging",
    0xB9: "Power Stew bubbling",
    0xBA: "Screen wipe",
    0xBB: "Machinery [LOOPS]",
    0xBC: "Ozzie's barrier shattering",
    0xBD: "Ozzie falling",
    0xBE: "Masamune [LOOPS]",
    0xBF: "Masamune light beam [LOOPS]",
    0xC0: "Crane chain [LOOPS]",
    0xC1: "Unknown - NOT USED IN EVENTS",
    0xC2: "Magic Cave splits",
    0xC3: "Keeper's Dome Epoch warp [LOOPS]",
    0xC4: "Robot computing 1",
    0xC5: "Tyrano roar",
    0xC6: "Robot computing 2",
    0xC7: "Robot computing slow",
    0xC8: "Epoch time warp",
    0xC9: "Teleport",
    0xCA: "Soda can bouncing",
    0xCB: "Blackbird cargo door opening [LOOPS]",
    0xCC: "Blackbird cargo door opened",
    0xCD: "Dinosaur skull opening",
    0xCE: "Epoch firing laser[LOOPS]",
    0xCF: "Rapid explosions [LOOPS]",
    0xD0: "Epoch powering up 2 [LOOPS]",
    0xD1: "Wormhole warp [LOOPS]",
    0xD2: "Epoch laser damaging Blackbird [LOOPS]",
    0xD3: "Robot computing 3",
    0xD4: "Large splash",
    0xD5: "Lavos beams destroying Zeal",
    0xD6: "Dinner chime",
    0xD7: "Power roast meal being prepared",
    0xD8: "Lavos breathing [LOOPS]",
    0xD9: "Epoch preparing to fly at Lavos [LOOPS]",
    0xDA: "Epoch flying into Lavos Mode 7 scene (3rd person side view) [LOOPS]",
    0xDB: "Epoch flying into Lavos Mode 7 scene (1st person) [LOOPS]",
    0xDC: "Epoch crashes into Lavos",
    0xDD: "Octo enemy",
    0xDE: "UNUSED",
    0xDF: "Light beams",
    0xE0: "Top of Black Omen [LOOPS]",
    0xE1: "Mammon Machine [LOOPS]",
    0xE2: "Lavos 2nd form [LOOPS]",
    0xE3: "Lavos 2nd form defeated",
    0xE4: "Unknown - NOT USED IN EVENTS",
    0xE5: "Explosion engulfing Black Omen",
    0xE6: "Lavos eruption explosion",
    0xE7: "Computer analyzing map 1",
    0xE8: "Computer analyzing map 2 [LOOPS]",
    0xE9: "Ending slideshow [LOOPS]",
    0xEA: "UNUSED",
    0xEB: "UNUSED",
    0xEC: "UNUSED",
    0xED: "UNUSED",
    0xEE: "UNUSED",
    0xEF: "UNUSED",
    0xF0: "UNUSED",
    0xF1: "UNUSED",
    0xF2: "UNUSED",
    0xF3: "UNUSED",
    0xF4: "Unknown - NOT USED IN EVENTS",
    0xF5: "UNUSED",
    0xF6: "UNUSED",
    0xF7: "UNUSED",
    0xF8: "UNUSED",
    0xF9: "UNUSED",
    0xFA: "UNUSED",
    0xFB: "UNUSED",
    0xFC: "UNUSED",
    0xFD: "UNUSED",
    0xFE: "Unknown [LOOPS] - NOT USED IN EVENTS",
    0xFF: "[END LOOP]",
}

mode7 = {
    0x0: "Bike Race",
    0x1: "Opening Credits",
    0x2: "Load Screen",
    0x3: "Glitched up screen",
    0x4: "Lavos crashes into the planet",
    0x5: "Giant gate at Magus Castle (glitched version)",
    0x6: "Scene where Epoch is going to crash through Lavos",
    0x7: "But the future refused to change",
    0x8: "But the future refused to change",
    0x9: "Bike Race (R&L button rotate mode)",
    0xA: "Fireworks animation from ending credits",
    0xB: "Fireworks animation from ending credits",
    0xC: "Ending Credits",
    0xD: "Ending Credits (Super fast version)",
    0x20: "Bike Race (turbo mode)",
    0x21: "Opening Credits",
    0x22: "Load Screen",
    0x23: "Glitched up screen",
    0x24: "Lavos crashes into the planet",
    0x25: "Giant gate at Magus Castle (glitched version)",
    0x40: "Bike Race cut shown in opening credits",
    0x60: "Bike Race cut shown in opening credits",
    0x80: "Wormhole scene (long version)",
    0x81: "Wormhole scene (short version)",
    0x82: "Wormhole scene (very short version)",
    0x83: "Wormhole scene (Lavos Core version)",
    0x84: "Wormhole scene (Lavos Core version)",
    0x85: "Wormhole scene (Lavos Core version)",
    0x86: "Wormhole scene (Lavos Core version)",
    0x87: "Wormhole scene (Lavos Core version)",
    0x88: "Wormhole scene (Lavos Core version)",
    0x89: "Wormhole scene (Lavos Core version)",
}